# page 45

In [29]:
import tensorflow as tf
import numpy as np

In [2]:
x = tf.linspace(10.0, 12.0, 3)
print(x)

Tensor("LinSpace:0", shape=(3,), dtype=float32)


In [5]:
y = tf.range(3, 18, 3)
z = tf.range(5)

In [6]:
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y))
    print(sess.run(z))
sess.close()

[ 10.  11.  12.]
[ 3  6  9 12 15]
[0 1 2 3 4]


# page 52 Placeholders

In [7]:
a = tf.placeholder(tf.float32, shape=[3])

In [17]:
b = tf.constant([5.,5.,5.])
c = a+b

In [20]:
with tf.Session() as sess:
    print(sess.run(c,feed_dict={a: [1.,2.,3.]}))

[ 6.  7.  8.]


In [21]:
x = tf.placeholder(tf.float32, shape=[1024,1024])
y = tf.matmul(x,x)

In [30]:
with tf.Session() as sess:
    feed = np.random.rand(1024,1024)
    print(sess.run(y,feed_dict={x: feed}))

[[ 245.70187378  250.09442139  252.0255127  ...,  251.16162109
   257.63220215  246.31724548]
 [ 254.04838562  255.60063171  251.54554749 ...,  252.01535034
   259.63745117  255.61764526]
 [ 254.72740173  257.32870483  262.77142334 ...,  261.35623169
   264.82315063  256.08532715]
 ..., 
 [ 254.37904358  262.7835083   259.7611084  ...,  258.13589478
   264.52859497  257.33917236]
 [ 251.95150757  251.5332489   250.81248474 ...,  257.78451538
   256.92297363  247.48204041]
 [ 248.10185242  248.25042725  250.97364807 ...,  252.4581604   248.09286499
   242.05293274]]


### Tensorflow feed 실행 예시 
Session은 feed 일 경우는 feed_dict으로 처리 값을 할당해야 함


In [35]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [36]:
x = tf.add(a,b)
y = tf.multiply(a,b)

In [38]:
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(x, feed_dict={a: 2.5, b: 3.5}))
    print(sess.run(y, feed_dict={a: 5.0, b: 1.7}))


6.0
8.5


# page 58 출력 포맷 지정하기


In [39]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

bias = tf.Variable(1.0)

In [40]:
y_pred = x**2 + bias

loas = (y-y_pred)**2

In [42]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print('Loss(x,y)=%16.8f' % sess.run(loas, feed_dict={x: 3.0, y: 5}))
    print('pred_y(x)=%16.8f' % sess.run(y_pred, feed_dict={x: 3.0}))
    print('bias     =%16.8f' % sess.run(bias))

Loss(x,y)=     25.00000000
pred_y(x)=     10.00000000
bias     =      1.00000000
